import * as ex from "excalibur";

export const Resources = {
  GameFont: new ex.FontSource("./fonts/game_font.ttf", "Game Font"),
  Player: new ex.ImageSource("./assets/player/player.png"),
  PlayerWalk1: new ex.ImageSource("./assets/player/player_walk1.png"),
  PlayerWalk2: new ex.ImageSource("./assets/player/player_walk2.png"),
  PlayerJump: new ex.ImageSource("./assets/player/player_jump.png"),
  PlayerCrouch: new ex.ImageSource("./assets/player/player_crouch.png"),
  PlayerUseTool1: new ex.ImageSource("./assets/player/player_use_tool1.png"),
  PlayerUseTool2: new ex.ImageSource("./assets/player/player_use_tool2.png"),
  PlayerUseTool3: new ex.ImageSource("./assets/player/player_use_tool3.png"),
  PlayerUseTool4: new ex.ImageSource("./assets/player/player_use_tool4.png"),
  PlayerUseTool5: new ex.ImageSource("./assets/player/player_use_tool5.png"),
  BronzePickaxe: new ex.ImageSource("./assets/tools/bronze_pickaxe.png"),
  BronzeSword: new ex.ImageSource("./assets/tools/bronze_sword.png"),
  BronzeSwordItem: new ex.ImageSource("./assets/items/bronze_sword.png"),
  Slime: new ex.ImageSource("./assets/mobs/slime.png"),
  BlockBreak1: new ex.ImageSource("./assets/effects/block_break1.png"),
  BlockBreak2: new ex.ImageSource("./assets/effects/block_break2.png"),
  BlockBreak3: new ex.ImageSource("./assets/effects/block_break3.png"),
  BlockBreak4: new ex.ImageSource("./assets/effects/block_break4.png"),
  Smash1: new ex.ImageSource("./assets/effects/smash_1.png"),
  Smash2: new ex.ImageSource("./assets/effects/smash_2.png"),
  Smash3: new ex.ImageSource("./assets/effects/smash_3.png"),
  Smash4: new ex.ImageSource("./assets/effects/smash_4.png"),
  HeartFull: new ex.ImageSource("./assets/ui/heart_full.png"),
  HeartHalf: new ex.ImageSource("./assets/ui/heart_half.png"),
  HeartEmpty: new ex.ImageSource("./assets/ui/heart_empty.png"),
  BuildIcon: new ex.ImageSource("./assets/ui/build_icon.png"),
  CombatIcon: new ex.ImageSource("./assets/ui/combat_icon.png"),
  InventoryBlockSlot: new ex.ImageSource("./assets/ui/inventory_block_slot.png"),
  InventoryWeaponSlot: new ex.ImageSource("./assets/ui/inventory_weapon_slot.png"),
  ThoughtBubbleSleep: new ex.ImageSource("./assets/ui/thought_bubble_sleep.png"),
  Block: new ex.ImageSource("./assets/blocks/block.png"),
  Grass: new ex.ImageSource("./assets/blocks/grass.png"),
  Dirt: new ex.ImageSource("./assets/blocks/dirt.png"),
  Lamp: new ex.ImageSource("./assets/blocks/block.png"),
  Stone: new ex.ImageSource("./assets/blocks/stone.png"),
  Bedrock: new ex.ImageSource("./assets/blocks/bedrock.png"),
} as const;
